### ISSUE TITLE
A black round this product

### ISSUE THREAD

**Issue by Lolothepro** [TechDevOnGitHub/Lux-Shader#2]
A black round this product
![2022-02-16_16 38 42](https://user-images.githubusercontent.com/68275908/154300345-e7703479-c61a-4d1f-90f6-c63a03a43ef2.png)

**Comment by TechDevOnGitHub** [comment]
This is currently a known issue. As mentioned in the repository description, the version of the shader currently pushed to the GitHub repository is not the same as the latest development version owned by me. Chances are high, that this issue will be resolved, when the latest version will be released. I will keep this in mind though.
